Kotlin. Homework #2. Task #1
aadaa-fgtaa/ktShallowSizePlugin pull request #1
Opened 2022-03-23 20:44 UTC by aadaa-fgtaa

2022-03-28 08:34 UTC, illided requested changes

2022-03-28 08:34 UTC, illided commented on .github/workflows/build.yml
> +        run: ./gradlew detekt
Мне тут подсказали что еще в идеале чтобы вы научились эти конфиги сами создавать)
Поэтому добавь сюда еще пожалуйста например скачивание [тест репортов](https://github.com/actions/upload-artifact) или настройку детекта.

2022-03-28 08:34 UTC, illided commented on shallowSizePlugin/src/main/kotlin/spbu/kotlin/shallow/plugin/AddShallowSizeMethod.kt
> +                    val func = clazz.functions.find { it.name.identifier == "shallowSize" } ?: throw shallowSizeNotFound
Также стоит проверить что у функции нет параметров. Всю эту проверку можно даже инкапсулировать в отдельную функцию

2022-03-28 08:34 UTC, illided commented on shallowSizePlugin/src/main/kotlin/spbu/kotlin/shallow/plugin/AddShallowSizeMethod.kt
> +                    val make = DeclarationIrBuilder(pluginContext, func.symbol)
Давай переименуем хотя бы в builder

2022-03-28 08:34 UTC, illided commented on shallowSizePlugin/src/main/kotlin/spbu/kotlin/shallow/plugin/AddShallowSizeMethod.kt
> +private val shallowSizeNotFound =
Очень хитрый способ избежать сообщения от детекта) 
Но давай так не будем делать. Либо кинь другое исключение, либо сделай свое (что то типо `ShallowSizeException`)

2022-03-28 08:34 UTC, illided commented on shallowSizePlugin/src/main/kotlin/spbu/kotlin/shallow/plugin/AddShallowSizeMethod.kt
> +    this.isBoolean() -> 1
Давай тоже в константу вынесем

2022-03-30 15:50 UTC, aadaa-fgtaa commented on shallowSizePlugin/src/main/kotlin/spbu/kotlin/shallow/plugin/AddShallowSizeMethod.kt
> +private val shallowSizeNotFound =
`IllegalStateException` пойдет?

2022-03-31 17:10 UTC, illided commented on shallowSizePlugin/src/main/kotlin/spbu/kotlin/shallow/plugin/AddShallowSizeMethod.kt
> +private val shallowSizeNotFound =
Думаю вполне

2022-03-31 17:11 UTC, illided approved these changes
Сейчас все круто. Поправь только то исключение
Кидаю тебя на Настю

2022-04-04 07:36 UTC, nbirillo requested changes
Одно небольшое замечание

2022-04-04 07:36 UTC, nbirillo commented on shallowSizePlugin/src/main/kotlin/spbu/kotlin/shallow/plugin/AddShallowSizeMethod.kt
> +    func.name.identifier == "shallowSize" && func.valueParameters.isEmpty()
В идеале имя функции тоже вынести в константу и использовать тут и в генерации декларации, чтобы точно избежать ошибок

2022-04-19 07:49 UTC, nbirillo approved these changes

2022-04-19 07:49 UTC, merged